In [74]:
x = [1,3,4]
x.mean() # 오류 발생 !

AttributeError: ignored

In [75]:
import numpy as np
x = np.array([1,3,5])
print(x.mean()) # 평균값

3.0


In [76]:
print(x.shape) # 3개의 원소가 있는 1차원 배열열

(3,)


In [77]:
# 퀴즈 9.1
a = np.array([[1, 2, 3],[2, 3, 4]]) # 각각 3개의 원소로 구성된 2개의 원소를 가진 numpy 배열 a
print(a.shape) # 배열의 정보를 다음과 같이 출력 - 2x3 배열열 퀴즈 9.1
a = np.array([[1, 2, 3],[2, 3, 4]]) # 각각 3개의 원소로 구성된 2개의 원소를 가진 numpy 배열 a
print(a.shape) # 배열의 정보를 다음과 같이 출력 - 2x3 배열열

(2, 3)
(2, 3)


In [78]:
# array() , reshape()
x = np.array([1,3,5,7,9,11]).reshape(3,2) # 1,3,5,7,9,11 array를 3x2 배열로 변환
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [79]:
# ones() : 1로 이루어진 배열을 생성
y = np.ones([3,4])
print(y) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [80]:
x = np.array([[1,3,5], [2,4,6]])
print(x[1])
print(x[1].mean())
print(x.mean())
print(x.shape)

[2 4 6]
4.0
3.5
(2, 3)


In [81]:
# 퀴즈 9.2
list1 = [[1,11], [2,12], [3,13]]
print(list1[1][1])

12


In [82]:
# 모든 원소에 대한 두 번째 항목 읽어오기 모든 원소에 대한 두 번째 항목 읽어오기
list1 = [[1,11], [2,12], [3,13]]
np_ary = np.array(list1)
print(np_ary[:,1])

[11 12 13]


In [83]:
list1 = [[1,11],[2,12],[3,13]]
print(np.array(list1[:][0]))

[ 1 11]


In [84]:
import math
math.sqrt(2)

1.4142135623730951

In [85]:
# math.sqrt([2,3,4]) 안됨!
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [86]:
a = np.arange(15)  # 0~14까지의 정수를 가진 일차원 배열
b = a.reshape(3,5) # 일차원 배열을 이차원 배열로 재구성
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [87]:
# 퀴즈 9.4
a = np.arange(15).reshape(3,5)
print(a[1][1])

6


In [88]:
# 1차원 배열
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [89]:
# 2차원 배열 2차원 배열
zero_matrix = np.zeros((4,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [90]:
zero_vector = np.zeros(5)
zero_vector # 일차원 array 자체 출력

array([0., 0., 0., 0., 0.])

In [91]:
zero_matrix = np.zeros((5,3))
zero_matrix # 이차원 array 자체 출력

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
my_array = np.zeros(15).reshape(3,5)
my_array += 4 # 모든 항목에 4를 더해줌
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [93]:
# 전치행렬 - transpose()
ary = np.array([[1,2],[3,4]]) # [[1 2] [3 4]]
print(ary.transpose())

[[1 3]
 [2 4]]


In [94]:
# 퀴즈 9.5
x = [1, 2, 3]
y = [4, 5, 6]
z = x + y
print(z)

[1, 2, 3, 4, 5, 6]


In [95]:
# 퀴즈 9.6
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[5 7 9]


In [96]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
print(z)

[ 4 10 18]


In [97]:
# s = [1,2,3] - error!
s = np.array([1,2,3])
t = s + 1
print(t)

[2 3 4]


In [98]:
# 퀴즈 9.7
x = np.array([4,8,12])
y = np.array([2,4,6])
z = x / y # //를 사용하면 [2 2 2]가 출력될 것이다.
print(z)

[2. 2. 2.]


In [99]:
# 인덱싱
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:, 1])

[4 5 6]
[2 5 8]


In [100]:
x = np.array([[1,2,3], [4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,1]+y[:,1])

[ 5 11 17]


In [101]:
a = np.array([10,20,30,40,50,60,70])
# b = [10,20,30,40,50,60,70] 
i = [1,3,5]
print(a[i])
# print(b[i]) - error

[20 40 60]


In [102]:
# 퀴즈 9.8
a = np.array([10,20,30,40,50,60,70])
b = a[1:6:2] # b는 a의 동일한 부분을 가리킴
print('b:',b) 
b[1] = 10
print('b:',b)
print('a:',a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 10 50 60 70]


In [103]:
a = np.array([10,20,30,40,50,60,70])
b = np.array(a[1:6:2]) # b는 a의 동일한 부분을 가리킴
print('b:',b) 
b[1] = 10
print('b:',b)
print('a:',a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


In [104]:
a = np.array([10,20,30,40,50,60,70])
b = a > 50
print(b)

[False False False False False  True  True]


In [105]:
ary = np.random.random(5) # 0~1 사이의 무작위 수 5개 생성ry = np.random.random(5) # 0~1 사이의 무작위 수 5개 생성
print(ary)
print(np.all(ary >= 0.3)) # 모든 원소가 0.3보다 크냐?
print(np.any(ary > 0.7)) # 0.7보다 큰 원소가 있냐?
print(ary)
print(np.all(ary >= 0.3)) # 모든 원소가 0.3보다 크냐?
print(np.any(ary > 0.7)) # 0.7보다 큰 원소가 있냐?

[0.53699465 0.05976479 0.81775092 0.06239917 0.9011258 ]
False
True
[0.53699465 0.05976479 0.81775092 0.06239917 0.9011258 ]
False
True


In [106]:
# 퀴즈 9.9
height = np.array([173, 168, 171, 189, 179])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = (weight/(height**2))*10000
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [107]:
# 퀴즈 9.10
print(bmi>21)

[ True False  True  True  True]


In [108]:
np.linspace(0, 12, 4) # 0과 12를 포함한 4 간격의 값들

array([ 0.,  4.,  8., 12.])

In [109]:
np.linspace(0, 12, 4, retstep=True) # 마지막에 간격도 출력

(array([ 0.,  4.,  8., 12.]), 4.0)

In [110]:
np.linspace(0, 12, 4, endpoint=False) # 0부터 12 전까지 4개의 등간격으로 값 얻어냄

array([0., 3., 6., 9.])

In [111]:
np.logspace(np.log10(10), np.log10(100), 5) # 1~10 사이의 5개의 로그 값의 간격으로 원소를 구성성서

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [112]:
np.logspace(1,2,5) # log10(n)의 값을 알고 있을 때

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])